spring:
    jackson:
        serialization:
            INDENT_OUTPUT: true
    application:
        name: iot-service
    jpa:
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                temp:
                use_jdbc_metadata_defaults: false
    datasource:
        platform: postgres
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: mysecretpassword
        driver-class-name: org.postgresql.Driver

jwt:
    header: Authorization
    secret: mySecret
    expiration: 604800
    route:
        authentication:
            path: /auth
            refresh: /refresh
            logout: /logout

mqtt:
    serverip: tcp://192.168.43.73
    serverport: 1883
#tcp://192.168.178.16
server:
  port: 8000
